// ────────────────────────────────────────────────────────────────────────────
// worker/lib/orderFormPdfV2.ts
//
// Server-side renderer for the customer-facing Order Form PDF (v2).
//
// CONTEXT: The reps fed back that the PDF generated by the app was "very
// simple" compared to A-SAFE's classic Excel-derived quote (cover + brand
// collateral + Proposed Solutions + Quote-To-Supply + T&Cs). Tom's
// instruction: do NOT just copy that legacy format. The app captures
// per-vehicle impact calculations, site surveys, customer profile data and
// per-product safety factors that the old Excel quote didn't surface. The
// new PDF must:
//
//   1. Match A-SAFE's brand identity (yellow #FFC72C, dark headings,
//      professional layout).
//   2. Surface the value-add sections — Customer Profile, Vehicle Movements,
//      Impact Calculations, Per-Product Safety Factor, Site Survey
//      Appendix, Reciprocal Value Commitments — when the project carries
//      that data. Sections are CONDITIONAL: a minimal project still
//      produces a clean compact PDF; a full project produces the works.
//
// STRATEGY: Pure-TS PDF byte builder, identical pattern to
// `quoteDraftPdf.ts` and `pas13AlignmentReportPdf.ts`. Cloudflare Workers
// can't run pdfkit cleanly even with `nodejs_compat`, and html2canvas /
// jsPDF round-tripping is a client-side dance we want to retire from the
// customer artefact path. Base-14 PDF fonts (Helvetica, Helvetica-Bold)
// only — every PDF reader has them built in. ASCII / Latin-1 only;
// non-Latin chars degrade to "?".
//
// HARD WORDING RULES (matches the rest of the app):
//   - "PAS 13 aligned" / "borderline alignment" / "not PAS 13 aligned" —
//     never "compliant".
//   - No "DRAFT" banner. The customer-facing artefact is final-form. The
//     rep-only quote-draft PDF (quoteDraftPdf.ts) keeps its banner.
//   - Reference numbering is `ENG_<NetSuite-style>` — e.g.
//     `ENG_QUOAE000123`. The caller shoulders the prefix; this file
//     trusts whatever it receives.
//
// MODULAR PIPELINE: each section is a `(ctx, builder, input) => void`
// function that draws its content and updates the builder's cursor. The
// top-level `buildOrderFormPdf` wires them in the standard order. Adding
// a new section is a matter of: write a new helper, wire it in,
// conditionally render based on input shape.
// ────────────────────────────────────────────────────────────────────────────

import {
  pas13Verdict,
  type Verdict,
} from "../../shared/pas13Rules";
import {
  pas13Cite,
  type Pas13Citation,
  PAS13_PDF_URL,
} from "../../shared/pas13Citations";

// ─── Types ─────────────────────────────────────────────────────────────────

/** Customer-facing project + cart payload to render the order-form PDF. */
export interface OrderFormV2Input {
  /** ENG_-prefixed reference number — e.g. "ENG_QUOAE000123". */
  referenceNumber: string;
  /** Optional secondary reference (drawing ref, internal CRM number, etc.). */
  drawingRef?: string | null;
  /** ISO-encoded build moment. Goes on every page footer. */
  generatedAt: Date;

  /** Currency the prices are denominated in (AED / SAR / GBP / …). */
  currency: string;

  /** Customer-side data — drives the cover + Customer Profile panels. */
  customer: CustomerProfile;
  /** A-SAFE-side rep data — drives the cover's right-hand info column. */
  preparedBy: PreparedByInfo;

  /** Project name (cover headline). Falls back to the customer company name. */
  projectName?: string | null;
  projectLocation?: string | null;
  projectDescription?: string | null;

  /** When set, the Vehicle Movements section is rendered. */
  vehicleMovements?: VehicleMovementSummary | null;
  /** When set, the Impact Calculations summary is rendered. */
  impactCalculations?: ImpactCalculationSummary | null;

  /** Proposed solutions — one row per cart line item with optional safety. */
  proposedSolutions: ProposedSolutionLine[];

  /** Pricing tables — one block per zone (A / B / C / …). */
  pricing: PricingBlock;

  /** When set, renders the Reciprocal Value Commitments section. */
  reciprocalCommitments?: ReciprocalCommitmentItem[] | null;

  /** Approval block — Technical / Commercial / optional Marketing slots. */
  approvals: ApprovalsBlock;

  /** Optional site-survey appendix (renders as the last section). */
  siteSurveyAppendix?: SiteSurveyAppendix | null;

  /** App origin used for footer deep-links. */
  appOrigin: string;
}

export interface CustomerProfile {
  /** Customer company display name (e.g. "Dnata Cargo"). */
  companyName: string;
  /** Primary contact full name. */
  contactName?: string | null;
  contactRole?: string | null;
  contactEmail?: string | null;
  contactMobile?: string | null;
  /** Industry — "Logistics", "Cold Storage", … rendered when available. */
  industry?: string | null;
  /** Country / city — rendered when available. */
  country?: string | null;
  /** Site type — "Distribution Centre", "Manufacturing Plant", … */
  siteType?: string | null;
  /** Free-form fact strip — { label, value } pairs. */
  extraFacts?: Array<{ label: string; value: string }>;
}

export interface PreparedByInfo {
  name: string;
  jobTitle?: string | null;
  email?: string | null;
  mobile?: string | null;
  /** Company / division — e.g. "A-SAFE DWC LLC, Engage". */
  company?: string | null;
}

export interface VehicleMovementRow {
  /** Display name, e.g. "Counterbalance Forklift 2.5T". */
  name: string;
  massKg?: number | null;
  /** Maximum lift / load capacity in kg. */
  maxLoadKg?: number | null;
  /** Typical operating speed in km/h. */
  speedKmh?: number | null;
  /** Optional movement frequency / count narrative ("approx. 30 movements/hr"). */
  frequencyLabel?: string | null;
  /** PAS 13 internal class — "T1".."T4". */
  pas13Class?: string | null;
}

export interface VehicleMovementSummary {
  rows: VehicleMovementRow[];
  /** Highest computed kinetic energy on this site, in joules at 45°. */
  highestKeJoules: number;
  /** Approach angle the highest-KE was computed at (degrees). */
  highestKeAngleDeg: number;
}

export interface ImpactScenarioForReport {
  vehicleLabel: string;
  vehicleMassKg: number;
  loadMassKg: number;
  speedKmh: number;
  approachAngleDeg: number;
  /** KE at the actual approach angle. */
  appliedJoules: number;
  /** Reported KE at 45° (the A-SAFE / §6.3.2 convention). */
  joulesAt45: number;
  verdict: Verdict;
  safetyMarginPct: number;
}

export interface ImpactCalculationSummary {
  scenarios: ImpactScenarioForReport[];
  /** Optional joule reference levels for the bar plot (e.g. 11k, 17k, 30k J). */
  pas13Thresholds?: Array<{ label: string; joules: number }>;
  /** Citations to thread into the section footer. */
  citations: Pas13Citation[];
}

export interface ProposedSolutionLine {
  /** Section letter — "A", "B", "C" — drives the heading on the page. */
  sectionLabel: string;
  /** Application area — "Door", "Column", "Racking", "Wall", etc. */
  applicationArea: string;
  /** Product display name. */
  productName: string;
  /** SKU — rendered on the spec card; falls back to "—". */
  sku?: string | null;
  /** Family — used to label the spec card subtitle. */
  family?: string | null;
  /** Joule rating from the catalog at 45°. May be null when not published. */
  productImpactJoules?: number | null;
  /** Required joules from the project's impact calc — drives the safety pill. */
  requiredJoules?: number | null;
  /** A short feature-bullet array rendered inside the spec card. */
  features?: string[];
  /** Optional impact-zone string ("Up to 110 mm"). */
  impactZoneLabel?: string | null;

  /** Customer-uploaded site photo URL, if any. */
  sitePhotoUrl?: string | null;
  /** Stock product photo URL. */
  productPhotoUrl?: string | null;

  /** Quantity for the line — meters for `per_length`, count for `per_unit`. */
  quantity: number;
  /** "per_length" | "per_unit". */
  pricingMode: "per_length" | "per_unit";
  /** Unit price in `currency`. */
  unitPrice: number;
  /** Line extended price in `currency`. */
  extendedPrice: number;

  /** Optional rep-supplied notes shown beneath the spec card. */
  notes?: string | null;
}

export interface PricingBlockRow {
  sectionLabel: string;
  productName: string;
  /** Length-in-meters or unit count. */
  quantity: number;
  pricingMode: "per_length" | "per_unit";
  unitPrice: number;
  extendedPrice: number;
}

export interface PricingBlock {
  rows: PricingBlockRow[];
  goodsTotal: number;
  /** Door-to-door delivery + installation charge — rendered as a single line. */
  deliveryAndInstallation?: number;
  /** Optional service-care line item. */
  serviceCare?: { label: string; amount: number };
  /** Sum of all reciprocal value commitments (combined cap already applied). */
  reciprocalDiscount?: number;
  /** Other discount lines, rendered above the grand total. */
  otherDiscounts?: Array<{ label: string; amount: number }>;
  /** VAT in absolute terms (UAE = 5%, SAR = 15% — caller computes). */
  vatAmount?: number;
  vatPct?: number;
  /** Grand total — caller's final number. */
  grandTotal: number;
}

export interface ReciprocalCommitmentItem {
  title: string;
  description?: string | null;
  /** Discount % the commitment unlocks. Optional. */
  discountPct?: number | null;
}

export interface ApprovalsBlock {
  /** When true, the third Marketing block is rendered. */
  includeMarketing: boolean;
  technical?: SignatureBlock | null;
  commercial?: SignatureBlock | null;
  marketing?: SignatureBlock | null;
}

export interface SignatureBlock {
  signed: boolean;
  signedBy?: string | null;
  jobTitle?: string | null;
  signedAtIso?: string | null;
}

export interface SiteSurveyAppendixZone {
  zoneName: string;
  areaType?: string | null;
  observations?: string | null;
  damageNotes?: string | null;
  recommendations?: Array<{
    productName: string;
    /** Per-meter unit price for context (Sagarika feedback). */
    pricePerMeter?: number | null;
  }>;
  photoCount: number;
}

export interface SiteSurveyAppendix {
  surveyTitle: string;
  surveyDate?: string | null;
  zones: SiteSurveyAppendixZone[];
  layoutDrawingThumbnailNote?: string | null;
}

export interface OrderFormV2Output {
  pdf: Uint8Array;
  filename: string;
}

// ─── Public entry point ────────────────────────────────────────────────────

export function buildOrderFormPdfV2(input: OrderFormV2Input): OrderFormV2Output {
  const builder = new PdfBuilder();
  const ctx: RenderCtx = { y: 0, pageNum: 0, totalPages: 0 };

  // Section pipeline — order matches the spec.
  // Each section is a function that may emit one or more pages on the
  // builder. Conditional sections short-circuit on missing data.
  renderCoverPage(builder, ctx, input);
  renderCustomerProfile(builder, ctx, input);
  if (input.vehicleMovements && input.vehicleMovements.rows.length > 0) {
    renderVehicleMovements(builder, ctx, input, input.vehicleMovements);
  }
  if (input.impactCalculations && input.impactCalculations.scenarios.length > 0) {
    renderImpactCalculations(builder, ctx, input, input.impactCalculations);
  }
  renderBrandCollateral(builder, ctx, input);
  renderProposedSolutions(builder, ctx, input);
  renderPricing(builder, ctx, input);
  if (input.reciprocalCommitments && input.reciprocalCommitments.length > 0) {
    renderReciprocalCommitments(builder, ctx, input, input.reciprocalCommitments);
  }
  renderApprovals(builder, ctx, input);
  renderTermsAndConditions(builder, ctx, input);
  if (input.siteSurveyAppendix && input.siteSurveyAppendix.zones.length > 0) {
    renderSiteSurveyAppendix(builder, ctx, input, input.siteSurveyAppendix);
  }

  builder.finalise();
  return {
    pdf: builder.bytes(),
    filename: filenameFor(input.referenceNumber),
  };
}

export function filenameFor(referenceNumber: string): string {
  const safe = referenceNumber.replace(/[^A-Za-z0-9._-]+/g, "_");
  return `A-SAFE_Order_Form-${safe}.pdf`;
}

// ─── Section: cover page ───────────────────────────────────────────────────

function renderCoverPage(
  pdf: PdfBuilder,
  ctx: RenderCtx,
  input: OrderFormV2Input,
): void {
  pdf.startPage();

  // Yellow header bar with A-SAFE wordmark + ORDER FORM
  pdf.fillRect(0, PAGE_H - 60, PAGE_W, 60, ASAFE_YELLOW);
  pdf.text("A-SAFE", MARGIN_X, PAGE_H - 38, {
    font: "Helvetica-Bold",
    size: 28,
    color: BLACK,
  });
  pdf.text("ENGAGE", MARGIN_X + 110, PAGE_H - 38, {
    font: "Helvetica-Bold",
    size: 14,
    color: BLACK,
  });
  pdf.text("ORDER FORM", PAGE_W - MARGIN_X, PAGE_H - 38, {
    font: "Helvetica-Bold",
    size: 16,
    color: BLACK,
    align: "right",
  });

  // Title block — project name centred, customer company beneath.
  let y = PAGE_H - 110;
  const title = (input.projectName || input.customer.companyName || "Order Form").trim();
  pdf.text(title, PAGE_W / 2, y, {
    font: "Helvetica-Bold",
    size: 22,
    color: BLACK,
    align: "center",
  });
  y -= 22;
  if (input.customer.companyName) {
    pdf.text(input.customer.companyName.toUpperCase(), PAGE_W / 2, y, {
      font: "Helvetica-Bold",
      size: 12,
      color: GREY,
      align: "center",
    });
    y -= 16;
  }
  if (input.projectLocation) {
    pdf.text(input.projectLocation, PAGE_W / 2, y, {
      size: 10,
      color: GREY,
      align: "center",
    });
    y -= 14;
  }

  // Hero "image" — render a flat coloured panel with a stylised diagram
  // since we have no PNG/JPEG decoder on the Worker. Keeps the cover
  // page from feeling sparse without dragging in image embedding.
  y -= 6;
  const heroH = 200;
  pdf.fillRect(MARGIN_X, y - heroH, PAGE_W - 2 * MARGIN_X, heroH, FAINT_GREY);
  // Simple bar pattern hinting at a barrier render.
  for (let i = 0; i < 8; i++) {
    const x0 = MARGIN_X + 18 + i * 60;
    pdf.fillRect(x0, y - heroH + 30, 8, heroH - 60, ASAFE_YELLOW);
  }
  pdf.fillRect(MARGIN_X, y - heroH + 24, PAGE_W - 2 * MARGIN_X, 4, BLACK);
  pdf.text(
    "Engineered Safety - Pedestrian + Vehicle Separation",
    PAGE_W / 2,
    y - heroH + 8,
    { font: "Helvetica-Bold", size: 9, color: BLACK, align: "center" },
  );
  y -= heroH + 14;

  // Two-column info table — LEFT = customer, RIGHT = A-SAFE rep.
  const colW = (PAGE_W - 2 * MARGIN_X - 14) / 2;
  const leftX = MARGIN_X;
  const rightX = MARGIN_X + colW + 14;
  const colTopY = y;
  const labelColor = GREY;
  const valueColor = BLACK;

  pdf.fillRect(leftX, y - 18, colW, 18, ASAFE_YELLOW);
  pdf.text("PROJECT DETAILS", leftX + 10, y - 12, {
    font: "Helvetica-Bold",
    size: 9,
    color: BLACK,
  });
  pdf.fillRect(rightX, y - 18, colW, 18, ASAFE_YELLOW);
  pdf.text("PREPARED BY", rightX + 10, y - 12, {
    font: "Helvetica-Bold",
    size: 9,
    color: BLACK,
  });
  y -= 26;

  const dateStr = formatDate(input.generatedAt);
  const left: Array<[string, string]> = [
    ["Project Ref", input.referenceNumber],
    ["Date", dateStr],
    ["Drawing Ref", input.drawingRef || "—"],
    ["Client Name", input.customer.companyName || "—"],
    ["Attention", input.customer.contactName || "—"],
    ["Job Title", input.customer.contactRole || "—"],
    ["Email", input.customer.contactEmail || "—"],
    ["Mobile", input.customer.contactMobile || "—"],
  ];
  const right: Array<[string, string]> = [
    ["Quote Ref", input.referenceNumber],
    ["Division", input.preparedBy.company || "A-SAFE Engage"],
    ["Representative", input.preparedBy.name || "—"],
    ["Job Title", input.preparedBy.jobTitle || "—"],
    ["Email", input.preparedBy.email || "—"],
    ["Mobile", input.preparedBy.mobile || "—"],
  ];

  // Layout the two columns side-by-side. Each column owns its own y cursor;
  // the page y resumes from the lower of the two when both finish.
  const drawColumn = (
    items: Array<[string, string]>,
    x0: number,
    yStart: number,
  ): number => {
    let yy = yStart;
    for (const [label, value] of items) {
      pdf.text(label.toUpperCase(), x0 + 4, yy, {
        font: "Helvetica-Bold",
        size: 7,
        color: labelColor,
      });
      pdf.text(truncate(value, 42), x0 + 4, yy - 11, {
        size: 9.5,
        color: valueColor,
      });
      pdf.fillRect(x0 + 4, yy - 16, colW - 8, 0.4, FAINT_GREY);
      yy -= 24;
    }
    return yy;
  };

  const leftEnd = drawColumn(left, leftX, y);
  const rightEnd = drawColumn(right, rightX, y);
  ctx.y = Math.min(leftEnd, rightEnd);

  // Bottom yellow strip
  const stripH = 4;
  pdf.fillRect(MARGIN_X, MARGIN_BOTTOM + 30, PAGE_W - 2 * MARGIN_X, stripH, ASAFE_YELLOW);

  renderFooter(pdf, ctx, input);
}

// ─── Section: customer profile overview ────────────────────────────────────

function renderCustomerProfile(
  pdf: PdfBuilder,
  ctx: RenderCtx,
  input: OrderFormV2Input,
): void {
  startSection(pdf, ctx, input, "Customer Profile");

  let y = ctx.y;
  pdf.text(
    "Snapshot of the operating environment this proposal has been engineered for.",
    MARGIN_X,
    y,
    { size: 9, color: GREY },
  );
  y -= 18;

  // Two-column "fact strip" of company-level data.
  const facts: Array<[string, string]> = [];
  facts.push(["Company", input.customer.companyName || "—"]);
  if (input.customer.contactName) {
    facts.push([
      "Primary contact",
      `${input.customer.contactName}${
        input.customer.contactRole ? ` - ${input.customer.contactRole}` : ""
      }`,
    ]);
  }
  if (input.customer.industry) facts.push(["Industry", input.customer.industry]);
  if (input.customer.country) facts.push(["Country", input.customer.country]);
  if (input.customer.siteType) facts.push(["Site type", input.customer.siteType]);
  if (input.projectLocation) facts.push(["Project location", input.projectLocation]);
  if (input.projectDescription)
    facts.push(["Scope", truncate(input.projectDescription, 90)]);
  for (const f of input.customer.extraFacts ?? []) {
    facts.push([f.label, f.value]);
  }

  const colW = (PAGE_W - 2 * MARGIN_X - 12) / 2;
  let leftY = y;
  let rightY = y;
  facts.forEach((row, idx) => {
    const isLeft = idx % 2 === 0;
    const x0 = isLeft ? MARGIN_X : MARGIN_X + colW + 12;
    const yy = isLeft ? leftY : rightY;
    pdf.text(row[0].toUpperCase(), x0 + 4, yy, {
      font: "Helvetica-Bold",
      size: 7,
      color: GREY,
    });
    pdf.text(truncate(row[1], 60), x0 + 4, yy - 11, {
      size: 9,
      color: BLACK,
    });
    pdf.fillRect(x0 + 4, yy - 16, colW - 8, 0.3, FAINT_GREY);
    if (isLeft) leftY -= 22;
    else rightY -= 22;
  });
  y = Math.min(leftY, rightY) - 6;

  // Narrative panel — light yellow tint, short rationale paragraph.
  if (
    input.customer.industry ||
    input.customer.siteType ||
    input.projectDescription
  ) {
    if (y < MARGIN_BOTTOM + 80) {
      newPage(pdf, ctx, input);
      y = ctx.y;
    }
    const blockH = 60;
    pdf.fillRect(MARGIN_X, y - blockH, PAGE_W - 2 * MARGIN_X, blockH, ASAFE_YELLOW_TINT);
    const lines: string[] = [];
    if (input.customer.industry || input.customer.siteType) {
      const parts: string[] = [];
      if (input.customer.industry) parts.push(input.customer.industry);
      if (input.customer.siteType) parts.push(input.customer.siteType.toLowerCase());
      lines.push(
        `${input.customer.companyName} operates a ${parts.join(" / ")} environment` +
          (input.projectLocation ? ` in ${input.projectLocation}` : "") +
          ".",
      );
    }
    if (input.projectDescription) {
      lines.push(truncate(input.projectDescription, 200));
    } else {
      lines.push(
        "This proposal pairs PAS 13:2017-aligned barriers with the vehicle and impact data captured in the A-SAFE Engage app.",
      );
    }
    let ly = y - 16;
    for (const line of lines) {
      const wrapped = wrapLines(line, 110);
      for (const w of wrapped) {
        if (ly < y - blockH + 6) break;
        pdf.text(w, MARGIN_X + 12, ly, { size: 9, color: BLACK });
        ly -= 11;
      }
    }
    y -= blockH + 8;
  }

  ctx.y = y;
  renderFooter(pdf, ctx, input);
}

// ─── Section: vehicle movements on site ────────────────────────────────────

function renderVehicleMovements(
  pdf: PdfBuilder,
  ctx: RenderCtx,
  input: OrderFormV2Input,
  vm: VehicleMovementSummary,
): void {
  startSection(pdf, ctx, input, "Vehicle Movements On Site");
  let y = ctx.y;

  pdf.text(
    `Captured from the impact-energy calculator. Highest kinetic energy: ${Math.round(vm.highestKeJoules).toLocaleString()} J at ${vm.highestKeAngleDeg}° (PAS 13:2017 §6.1 - KE = 0.5m(v sinθ)²).`,
    MARGIN_X,
    y,
    { size: 9, color: GREY },
  );
  y -= 16;

  // Table header
  const cols: TableColumn[] = [
    { x: MARGIN_X, w: 170, label: "Vehicle" },
    { x: MARGIN_X + 170, w: 60, label: "Mass (kg)", align: "right" },
    { x: MARGIN_X + 230, w: 60, label: "Max load (kg)", align: "right" },
    { x: MARGIN_X + 290, w: 60, label: "Speed (km/h)", align: "right" },
    { x: MARGIN_X + 350, w: 80, label: "Frequency" },
    { x: MARGIN_X + 430, w: 60, label: "PAS 13 class" },
  ];
  pdf.fillRect(MARGIN_X, y - 14, PAGE_W - 2 * MARGIN_X, 14, BLACK);
  for (const col of cols) {
    const labelX = col.align === "right" ? col.x + col.w - 4 : col.x + 4;
    pdf.text(col.label, labelX, y - 10, {
      font: "Helvetica-Bold",
      size: 7,
      color: ASAFE_YELLOW,
      align: col.align,
    });
  }
  y -= 16;

  for (let i = 0; i < vm.rows.length; i++) {
    if (y < MARGIN_BOTTOM + 60) {
      newPage(pdf, ctx, input);
      y = ctx.y;
    }
    const row = vm.rows[i];
    if (i % 2 === 0) {
      pdf.fillRect(MARGIN_X, y - 18, PAGE_W - 2 * MARGIN_X, 18, FAINT_GREY);
    }
    // Tiny silhouette icon — rendered as a stylised rectangle since we
    // can't decode SVG. The detail page strips also use this approach.
    pdf.fillRect(cols[0].x + 4, y - 14, 22, 12, ASAFE_YELLOW);
    pdf.fillRect(cols[0].x + 6, y - 8, 4, 4, BLACK);
    pdf.fillRect(cols[0].x + 18, y - 8, 4, 4, BLACK);

    pdf.text(truncate(row.name, 36), cols[0].x + 32, y - 10, {
      size: 9,
      color: BLACK,
      font: "Helvetica-Bold",
    });
    pdf.text(
      row.massKg != null ? row.massKg.toLocaleString() : "—",
      cols[1].x + cols[1].w - 4,
      y - 10,
      { size: 9, color: BLACK, align: "right" },
    );
    pdf.text(
      row.maxLoadKg != null ? row.maxLoadKg.toLocaleString() : "—",
      cols[2].x + cols[2].w - 4,
      y - 10,
      { size: 9, color: BLACK, align: "right" },
    );
    pdf.text(
      row.speedKmh != null ? row.speedKmh.toFixed(1) : "—",
      cols[3].x + cols[3].w - 4,
      y - 10,
      { size: 9, color: BLACK, align: "right" },
    );
    pdf.text(truncate(row.frequencyLabel || "—", 18), cols[4].x + 4, y - 10, {
      size: 9,
      color: BLACK,
    });
    if (row.pas13Class) {
      pdf.fillRect(cols[5].x + 4, y - 14, 36, 12, BLACK);
      pdf.text(row.pas13Class, cols[5].x + 8, y - 10, {
        size: 8,
        color: ASAFE_YELLOW,
        font: "Helvetica-Bold",
      });
    }
    y -= 18;
  }

  // Narrative footer.
  y -= 6;
  pdf.fillRect(MARGIN_X, y - 38, PAGE_W - 2 * MARGIN_X, 38, ASAFE_YELLOW_TINT);
  const classCount = countDistinct(
    vm.rows.map((r) => r.pas13Class || "Unclassified"),
  );
  pdf.text(
    `This site has ${vm.rows.length} vehicle ${vm.rows.length === 1 ? "class" : "classes"} ` +
      `across ${classCount} PAS 13 ${classCount === 1 ? "tier" : "tiers"}. ` +
      `Highest kinetic energy: ${Math.round(vm.highestKeJoules).toLocaleString()} J ` +
      `at 45° per PAS 13:2017 Figure 17.`,
    MARGIN_X + 10,
    y - 14,
    { size: 9, color: BLACK },
  );
  pdf.text(
    "All barrier recommendations on the next pages are sized against this envelope.",
    MARGIN_X + 10,
    y - 28,
    { size: 9, color: BLACK },
  );
  y -= 46;

  ctx.y = y;
  renderFooter(pdf, ctx, input);
}

// ─── Section: impact calculations summary ──────────────────────────────────

function renderImpactCalculations(
  pdf: PdfBuilder,
  ctx: RenderCtx,
  input: OrderFormV2Input,
  ic: ImpactCalculationSummary,
): void {
  startSection(pdf, ctx, input, "Impact Calculations Summary");
  let y = ctx.y;

  pdf.text(
    "PAS 13:2017 §6.1 - KE = 0.5m(v sinθ)². Each scenario is reported at the actual approach angle and at the 45° reference convention used by PAS 13 product testing.",
    MARGIN_X,
    y,
    { size: 9, color: GREY },
  );
  y -= 18;

  const cols: TableColumn[] = [
    { x: MARGIN_X, w: 170, label: "Scenario" },
    { x: MARGIN_X + 170, w: 50, label: "Mass (kg)", align: "right" },
    { x: MARGIN_X + 220, w: 60, label: "Speed (km/h)", align: "right" },
    { x: MARGIN_X + 280, w: 50, label: "Angle", align: "right" },
    { x: MARGIN_X + 330, w: 60, label: "KE @ 45°", align: "right" },
    { x: MARGIN_X + 390, w: 50, label: "Margin", align: "right" },
    { x: MARGIN_X + 440, w: 80, label: "Verdict" },
  ];
  pdf.fillRect(MARGIN_X, y - 14, PAGE_W - 2 * MARGIN_X, 14, BLACK);
  for (const col of cols) {
    const labelX = col.align === "right" ? col.x + col.w - 4 : col.x + 4;
    pdf.text(col.label, labelX, y - 10, {
      font: "Helvetica-Bold",
      size: 7,
      color: ASAFE_YELLOW,
      align: col.align,
    });
  }
  y -= 16;

  for (let i = 0; i < ic.scenarios.length; i++) {
    if (y < MARGIN_BOTTOM + 80) {
      newPage(pdf, ctx, input);
      y = ctx.y;
    }
    const s = ic.scenarios[i];
    if (i % 2 === 0) {
      pdf.fillRect(MARGIN_X, y - 18, PAGE_W - 2 * MARGIN_X, 18, FAINT_GREY);
    }
    pdf.text(truncate(s.vehicleLabel, 38), cols[0].x + 4, y - 10, {
      size: 9,
      color: BLACK,
    });
    pdf.text(
      (s.vehicleMassKg + s.loadMassKg).toLocaleString(),
      cols[1].x + cols[1].w - 4,
      y - 10,
      { size: 9, color: BLACK, align: "right" },
    );
    pdf.text(s.speedKmh.toFixed(1), cols[2].x + cols[2].w - 4, y - 10, {
      size: 9,
      color: BLACK,
      align: "right",
    });
    pdf.text(`${s.approachAngleDeg}°`, cols[3].x + cols[3].w - 4, y - 10, {
      size: 9,
      color: BLACK,
      align: "right",
    });
    pdf.text(
      `${Math.round(s.joulesAt45).toLocaleString()} J`,
      cols[4].x + cols[4].w - 4,
      y - 10,
      { size: 9, color: BLACK, align: "right", font: "Helvetica-Bold" },
    );
    const marginColour =
      s.verdict === "aligned"
        ? GREEN_DARK
        : s.verdict === "borderline"
          ? AMBER_DARK
          : RED_DARK;
    pdf.text(
      `${s.safetyMarginPct.toFixed(1)}%`,
      cols[5].x + cols[5].w - 4,
      y - 10,
      { size: 9, color: marginColour, align: "right", font: "Helvetica-Bold" },
    );
    pdf.fillRect(cols[6].x + 4, y - 14, 70, 12, marginColour);
    pdf.text(verdictLabel(s.verdict), cols[6].x + 8, y - 10, {
      size: 8,
      color: WHITE,
      font: "Helvetica-Bold",
    });
    y -= 18;
  }

  // Bar plot — relative position of each scenario against PAS 13 thresholds.
  // Layout per scenario row:
  //   [label] (left column)        [coloured bar] [value]   (right column)
  // Label and bar sit on different x columns so they never overlap. Bar
  // height is small (5pt) so labels sit comfortably to the left.
  const rowsPerScenario = 22;
  const plotH = 36 + Math.max(1, ic.scenarios.length) * rowsPerScenario;
  if (y < MARGIN_BOTTOM + plotH + 30) {
    newPage(pdf, ctx, input);
    y = ctx.y;
  }
  const plotW = PAGE_W - 2 * MARGIN_X;
  pdf.fillRect(MARGIN_X, y - plotH, plotW, plotH, FAINT_GREY);
  pdf.text("Where each scenario sits on the PAS 13 envelope", MARGIN_X + 8, y - 12, {
    font: "Helvetica-Bold",
    size: 9,
    color: BLACK,
  });
  // Compute the X-axis maximum: max of scenario joules + 25%.
  const allJoules = ic.scenarios.map((s) => s.joulesAt45);
  const allThresholds = (ic.pas13Thresholds || []).map((t) => t.joules);
  let xMax = Math.max(0, ...allJoules, ...allThresholds) * 1.25;
  if (xMax <= 0) xMax = 30000;
  // Reserve a left column for the scenario labels so they don't sit on top
  // of the bars.
  const labelColW = 170;
  const valueColW = 60;
  const x0 = MARGIN_X + 8 + labelColW;
  const x1 = MARGIN_X + plotW - 8 - valueColW;
  // Threshold tick marks across the bar plotting region.
  for (const t of ic.pas13Thresholds || []) {
    if (t.joules <= 0) continue;
    const xx = x0 + ((x1 - x0) * t.joules) / xMax;
    if (xx > x1) continue;
    pdf.fillRect(xx, y - plotH + 12, 0.6, plotH - 28, GREY);
    pdf.text(t.label, xx + 2, y - plotH + 6, { size: 7, color: GREY });
  }
  // Scenario rows
  let barY = y - 28;
  for (const s of ic.scenarios) {
    const w = ((x1 - x0) * s.joulesAt45) / xMax;
    const colour =
      s.verdict === "aligned"
        ? GREEN_DARK
        : s.verdict === "borderline"
          ? AMBER_DARK
          : RED_DARK;
    // Label on the left, bar in the middle, value on the right.
    pdf.text(truncate(s.vehicleLabel, 36), MARGIN_X + 8, barY - 1, {
      size: 8,
      color: BLACK,
    });
    pdf.fillRect(x0, barY - 5, Math.max(2, w), 5, colour);
    pdf.text(
      `${Math.round(s.joulesAt45).toLocaleString()} J`,
      x1 + valueColW,
      barY - 1,
      { size: 8, color: BLACK, align: "right" },
    );
    barY -= rowsPerScenario;
    if (barY < y - plotH + 14) break;
  }
  y -= plotH + 8;

  // Citation strip
  if (ic.citations.length > 0) {
    const citeStr =
      "Cited: " +
      ic.citations
        .slice(0, 5)
        .map((c) => `§${c.section}`)
        .join("  ") +
      " - " +
      "Verdicts use 30% safety-margin threshold; conservative interpretation throughout.";
    pdf.text(citeStr, MARGIN_X, y, { size: 8, color: BLUE_LINK });
    y -= 12;
  }

  ctx.y = y;
  renderFooter(pdf, ctx, input);
}

// ─── Section: brand collateral (compressed to 2 pages of distilled value) ──

function renderBrandCollateral(
  pdf: PdfBuilder,
  ctx: RenderCtx,
  input: OrderFormV2Input,
): void {
  // Page 1: Material Science + Energy Absorption
  startSection(pdf, ctx, input, "Why A-SAFE");
  let y = ctx.y;

  pdf.text(
    "Three reasons to specify polymer barriers engineered to PAS 13:2017.",
    MARGIN_X,
    y,
    { size: 9, color: GREY },
  );
  y -= 16;

  const cards: Array<{ heading: string; body: string }> = [
    {
      heading: "Material Science",
      body:
        "Memaplex polymer absorbs and dissipates impact energy then returns to its original shape - no permanent deformation, no costly steel replacement after every minor knock.",
    },
    {
      heading: "Energy Absorption System",
      body:
        "Bolted-together post + rail architecture transfers impact through specifically engineered components, isolating the floor slab from the impact and protecting the building structure.",
    },
    {
      heading: "PAS 13:2017 + TUV Tested",
      body:
        "Every barrier family is impact-tested under PAS 13:2017 protocol and TUV-witnessed. Joule ratings on the Solutions pages are independently certified, not marketing numbers.",
    },
  ];
  for (const card of cards) {
    if (y < MARGIN_BOTTOM + 70) {
      newPage(pdf, ctx, input);
      y = ctx.y;
    }
    const h = 56;
    pdf.fillRect(MARGIN_X, y - h, PAGE_W - 2 * MARGIN_X, h, FAINT_GREY);
    pdf.fillRect(MARGIN_X, y - h, 4, h, ASAFE_YELLOW);
    pdf.text(card.heading, MARGIN_X + 14, y - 16, {
      font: "Helvetica-Bold",
      size: 12,
      color: BLACK,
    });
    const wrapped = wrapLines(card.body, 110);
    let by = y - 30;
    for (const line of wrapped) {
      pdf.text(line, MARGIN_X + 14, by, { size: 9, color: BLACK });
      by -= 11;
      if (by < y - h + 6) break;
    }
    y -= h + 8;
  }

  // CO2 + Maintenance band — distilled value claim. Panel is tall enough
  // to contain the heading + two body lines without bleeding into the
  // following section. We split the heading column from the body column
  // so the heading reads as a label and the body fills the rest.
  if (y < MARGIN_BOTTOM + 80) {
    newPage(pdf, ctx, input);
    y = ctx.y;
  }
  const co2H = 50;
  pdf.fillRect(MARGIN_X, y - co2H, PAGE_W - 2 * MARGIN_X, co2H, BLACK);
  pdf.fillRect(MARGIN_X, y - co2H, 4, co2H, ASAFE_YELLOW);
  pdf.text("CO2 + MAINTENANCE", MARGIN_X + 14, y - 18, {
    font: "Helvetica-Bold",
    size: 10,
    color: ASAFE_YELLOW,
  });
  pdf.text(
    "Polymer barriers cut embodied CO2 by ~70% versus painted steel and",
    MARGIN_X + 14,
    y - 32,
    { size: 9, color: WHITE },
  );
  pdf.text(
    "remove the repaint / re-weld lifecycle that drives steel maintenance budgets.",
    MARGIN_X + 14,
    y - 44,
    { size: 9, color: WHITE },
  );
  y -= co2H + 12;

  ctx.y = y;
  renderFooter(pdf, ctx, input);
}

// ─── Section: proposed solutions (per-product, with safety pill) ───────────

function renderProposedSolutions(
  pdf: PdfBuilder,
  ctx: RenderCtx,
  input: OrderFormV2Input,
): void {
  startSection(pdf, ctx, input, "Proposed Solutions");
  let y = ctx.y;

  // Wrap the section intro so it sits comfortably inside the right margin
  // even on a 4-line truncation budget.
  const introWrapped = wrapLines(
    "Each application area is matched to a barrier family. Where the project carries an impact calculation, the safety factor is shown as a coloured pill alongside the spec card.",
    100,
  );
  for (const w of introWrapped) {
    pdf.text(w, MARGIN_X, y, { size: 9, color: GREY });
    y -= 11;
  }
  y -= 6;

  for (const line of input.proposedSolutions) {
    // Each line = one card. We need ~140pt of vertical space per card; if
    // there's not enough, push to a fresh page (preserve the section
    // banner).
    if (y < MARGIN_BOTTOM + 160) {
      newPage(pdf, ctx, input);
      y = ctx.y;
    }
    const cardH = 130;
    pdf.fillRect(MARGIN_X, y - cardH, PAGE_W - 2 * MARGIN_X, cardH, FAINT_GREY);

    // Section letter + title bar
    pdf.fillRect(MARGIN_X, y - 22, PAGE_W - 2 * MARGIN_X, 22, BLACK);
    pdf.text(line.sectionLabel, MARGIN_X + 10, y - 16, {
      font: "Helvetica-Bold",
      size: 14,
      color: ASAFE_YELLOW,
    });
    pdf.text(line.applicationArea, MARGIN_X + 32, y - 16, {
      font: "Helvetica-Bold",
      size: 11,
      color: WHITE,
    });
    pdf.text(`Solution: ${line.productName}`, PAGE_W - MARGIN_X - 10, y - 16, {
      font: "Helvetica-Bold",
      size: 10,
      color: ASAFE_YELLOW,
      align: "right",
    });

    // Photos — left = customer site, right = stock product. Slightly
    // narrower than first cut so the spec column (right) gets ~250pt of
    // room and feature lines stop truncating.
    const photoW = 120;
    const photoH = 80;
    // Left photo slot
    pdf.fillRect(MARGIN_X + 8, y - 22 - photoH - 8, photoW, photoH, WHITE);
    pdf.fillRect(MARGIN_X + 8, y - 22 - photoH - 8, photoW, photoH, FAINT_GREY);
    pdf.fillRect(MARGIN_X + 8, y - 22 - photoH - 8, 1, photoH, BLACK);
    pdf.fillRect(MARGIN_X + 8, y - 22 - 8, photoW, 1, BLACK);
    if (line.sitePhotoUrl) {
      pdf.text("[ site photo on file ]", MARGIN_X + 14, y - 22 - photoH / 2 + 4, {
        size: 8,
        color: GREY,
      });
    } else {
      // Two-line message — keeps each line inside the 140pt photo slot.
      pdf.text("Site photos will be added", MARGIN_X + 14, y - 22 - photoH / 2 + 8, {
        size: 8,
        color: GREY,
      });
      pdf.text("once the site is built", MARGIN_X + 14, y - 22 - photoH / 2 - 2, {
        size: 8,
        color: GREY,
      });
    }
    // Right photo slot — product hero
    const rightX = MARGIN_X + 8 + photoW + 8;
    pdf.fillRect(rightX, y - 22 - photoH - 8, photoW, photoH, ASAFE_YELLOW_TINT);
    pdf.fillRect(rightX + photoW / 2 - 4, y - 22 - 16, 8, photoH - 16, ASAFE_YELLOW);
    pdf.text("[ product render ]", rightX + 8, y - 22 - photoH / 2 + 4, {
      size: 8,
      color: GREY,
    });

    // Spec card (right of the product photo). The safety pill is anchored
    // to the bottom of the spec column, so we cap spec text just above
    // the pill's footprint to prevent overlap.
    const specX = rightX + photoW + 14;
    const specW = PAGE_W - MARGIN_X - 8 - specX;
    const pillW = 160;
    const pillH = 18;
    const pillY = y - cardH + 10;
    const specBottomY = pillY + pillH + 4;
    let sy = y - 22 - 14;
    // 8pt Helvetica avg glyph width ≈ 4.2pt — divide the column width
    // accordingly to fit the longest spec lines without truncation.
    const specMaxChars = Math.max(24, Math.floor(specW / 4.2));
    const writeSpecLine = (text: string, opts: TextOptions = {}) => {
      if (sy < specBottomY) return; // out of room — drop the rest, pill takes priority
      pdf.text(truncate(text, specMaxChars), specX, sy, {
        size: 8,
        color: BLACK,
        ...opts,
      });
      sy -= 10;
    };
    pdf.text(truncate(line.productName, specMaxChars), specX, sy, {
      font: "Helvetica-Bold",
      size: 11,
      color: BLACK,
    });
    sy -= 12;
    if (line.family) writeSpecLine(`Family: ${line.family}`, { color: GREY });
    if (line.sku) writeSpecLine(`SKU: ${line.sku}`, { color: GREY });
    if (line.productImpactJoules != null && line.productImpactJoules > 0) {
      writeSpecLine(
        `Impact: ${Math.round(line.productImpactJoules).toLocaleString()} J at 45°`,
        { color: BLACK, font: "Helvetica-Bold" },
      );
    } else {
      writeSpecLine("Impact rating: not published*", { color: AMBER_DARK });
    }
    if (line.impactZoneLabel) {
      writeSpecLine(`Impact zone: ${line.impactZoneLabel}`, { color: GREY });
    }
    for (const f of (line.features || []).slice(0, 2)) {
      writeSpecLine(`- ${f}`, { color: BLACK });
    }

    // Safety pill — bottom of the spec column, never overlapping spec text.
    if (line.requiredJoules != null && line.requiredJoules > 0) {
      const sf = computeSafetyFactor(line.productImpactJoules, line.requiredJoules);
      const isMissing = line.productImpactJoules == null || line.productImpactJoules <= 0;
      const colour = isMissing
        ? GREY
        : sf >= 1.5
          ? GREEN_DARK
          : sf >= 1.0
            ? AMBER_DARK
            : RED_DARK;
      const label = isMissing
        ? "Engineering review*"
        : `Safety factor ${(sf * 100).toFixed(0)}%${sf < 1 ? " (review)" : ""}`;
      pdf.fillRect(PAGE_W - MARGIN_X - 8 - pillW, pillY, pillW, pillH, colour);
      pdf.text(label, PAGE_W - MARGIN_X - 12, pillY + 5, {
        size: 9,
        font: "Helvetica-Bold",
        color: WHITE,
        align: "right",
      });
    }

    // Footnote on the card if the impact rating is missing.
    if (line.productImpactJoules == null || line.productImpactJoules <= 0) {
      pdf.text(
        "* No impact rating published. Engineering assessment available on request.",
        MARGIN_X + 12,
        y - cardH + 2,
        { size: 7, color: GREY },
      );
    }

    // Notes line beneath the card, if any.
    y -= cardH + 6;
    if (line.notes) {
      pdf.text(`Notes: ${truncate(line.notes, 130)}`, MARGIN_X + 4, y, {
        size: 8,
        color: GREY,
      });
      y -= 12;
    }
    y -= 6;
  }

  ctx.y = y;
  renderFooter(pdf, ctx, input);
}

// ─── Section: pricing ──────────────────────────────────────────────────────

function renderPricing(
  pdf: PdfBuilder,
  ctx: RenderCtx,
  input: OrderFormV2Input,
): void {
  startSection(pdf, ctx, input, "Quote To Supply");
  let y = ctx.y;

  pdf.text(
    `All prices are in ${input.currency.toUpperCase()}. Excluded items are flagged in the totals block. Pricing valid 30 days from the date on the cover.`,
    MARGIN_X,
    y,
    { size: 9, color: GREY },
  );
  y -= 16;

  // Group rows by sectionLabel
  const groups = new Map<string, PricingBlockRow[]>();
  for (const row of input.pricing.rows) {
    const arr = groups.get(row.sectionLabel) || [];
    arr.push(row);
    groups.set(row.sectionLabel, arr);
  }
  const sortedKeys = Array.from(groups.keys()).sort();

  // Column layout (Length / Qty / Unit / Total)
  const cols: TableColumn[] = [
    { x: MARGIN_X, w: 230, label: "Description" },
    { x: MARGIN_X + 230, w: 70, label: "Length / Qty", align: "right" },
    { x: MARGIN_X + 300, w: 90, label: `Unit (${input.currency.toUpperCase()})`, align: "right" },
    { x: MARGIN_X + 390, w: 130, label: `Total (${input.currency.toUpperCase()})`, align: "right" },
  ];

  const writeHeader = () => {
    pdf.fillRect(MARGIN_X, y - 14, PAGE_W - 2 * MARGIN_X, 14, BLACK);
    for (const col of cols) {
      const labelX = col.align === "right" ? col.x + col.w - 4 : col.x + 4;
      pdf.text(col.label, labelX, y - 10, {
        font: "Helvetica-Bold",
        size: 7,
        color: ASAFE_YELLOW,
        align: col.align,
      });
    }
    y -= 16;
  };

  for (const key of sortedKeys) {
    if (y < MARGIN_BOTTOM + 100) {
      newPage(pdf, ctx, input);
      y = ctx.y;
    }
    pdf.fillRect(MARGIN_X, y - 18, 28, 18, ASAFE_YELLOW);
    pdf.text(key, MARGIN_X + 10, y - 14, {
      font: "Helvetica-Bold",
      size: 11,
      color: BLACK,
    });
    pdf.text(
      `${(groups.get(key) || []).length} item${
        (groups.get(key) || []).length === 1 ? "" : "s"
      }`,
      MARGIN_X + 36,
      y - 14,
      { size: 9, color: GREY },
    );
    y -= 22;
    writeHeader();

    let groupTotal = 0;
    for (const row of groups.get(key) || []) {
      if (y < MARGIN_BOTTOM + 60) {
        newPage(pdf, ctx, input);
        y = ctx.y;
        writeHeader();
      }
      pdf.text(truncate(row.productName, 60), cols[0].x + 4, y - 10, {
        size: 9,
        color: BLACK,
      });
      const qtyStr =
        row.pricingMode === "per_length"
          ? `${row.quantity.toFixed(1)} m`
          : `x ${row.quantity}`;
      pdf.text(qtyStr, cols[1].x + cols[1].w - 4, y - 10, {
        size: 9,
        color: BLACK,
        align: "right",
      });
      pdf.text(formatMoney(row.unitPrice), cols[2].x + cols[2].w - 4, y - 10, {
        size: 9,
        color: BLACK,
        align: "right",
      });
      pdf.text(formatMoney(row.extendedPrice), cols[3].x + cols[3].w - 4, y - 10, {
        size: 9,
        color: BLACK,
        align: "right",
        font: "Helvetica-Bold",
      });
      pdf.fillRect(MARGIN_X, y - 14, PAGE_W - 2 * MARGIN_X, 0.3, FAINT_GREY);
      y -= 16;
      groupTotal += row.extendedPrice;
    }
    // Group sub-total
    pdf.text(`Sub-total ${key}`, cols[2].x + cols[2].w - 4, y - 10, {
      size: 9,
      color: GREY,
      align: "right",
    });
    pdf.text(formatMoney(groupTotal), cols[3].x + cols[3].w - 4, y - 10, {
      size: 10,
      color: BLACK,
      align: "right",
      font: "Helvetica-Bold",
    });
    y -= 20;
  }

  // Totals block
  if (y < MARGIN_BOTTOM + 130) {
    newPage(pdf, ctx, input);
    y = ctx.y;
  }
  pdf.fillRect(MARGIN_X, y - 1, PAGE_W - 2 * MARGIN_X, 1, BLACK);
  y -= 12;
  const totalsX = PAGE_W - MARGIN_X - 220;
  const totalsValueX = PAGE_W - MARGIN_X - 4;
  const writeTotal = (label: string, amount: number, opts: TextOptions = {}) => {
    pdf.text(label, totalsX, y, { size: 9, color: GREY, ...opts });
    pdf.text(`${input.currency.toUpperCase()} ${formatMoney(amount)}`, totalsValueX, y, {
      size: 9,
      color: BLACK,
      align: "right",
      ...opts,
    });
    y -= 12;
  };
  writeTotal("Goods Total", input.pricing.goodsTotal);
  if (
    typeof input.pricing.deliveryAndInstallation === "number" &&
    input.pricing.deliveryAndInstallation > 0
  ) {
    writeTotal(
      "Door-to-Door Delivery + Installation",
      input.pricing.deliveryAndInstallation,
    );
  }
  if (input.pricing.serviceCare) {
    writeTotal(input.pricing.serviceCare.label, input.pricing.serviceCare.amount);
  }
  for (const d of input.pricing.otherDiscounts || []) {
    writeTotal(d.label, -Math.abs(d.amount));
  }
  if (
    typeof input.pricing.reciprocalDiscount === "number" &&
    input.pricing.reciprocalDiscount > 0
  ) {
    writeTotal("Reciprocal Value Discount", -Math.abs(input.pricing.reciprocalDiscount));
  }
  if (typeof input.pricing.vatAmount === "number" && input.pricing.vatAmount > 0) {
    writeTotal(
      `VAT (${(input.pricing.vatPct ?? 0).toFixed(0)}%)`,
      input.pricing.vatAmount,
    );
  }
  // Grand total in a black band
  pdf.fillRect(totalsX - 6, y - 18, 226, 22, BLACK);
  pdf.text("GRAND TOTAL (Ex. VAT)", totalsX, y - 12, {
    size: 10,
    color: ASAFE_YELLOW,
    font: "Helvetica-Bold",
  });
  pdf.text(
    `${input.currency.toUpperCase()} ${formatMoney(input.pricing.grandTotal)}`,
    totalsValueX,
    y - 12,
    { size: 11, color: ASAFE_YELLOW, align: "right", font: "Helvetica-Bold" },
  );
  y -= 32;

  ctx.y = y;
  renderFooter(pdf, ctx, input);
}

// ─── Section: reciprocal commitments ───────────────────────────────────────

function renderReciprocalCommitments(
  pdf: PdfBuilder,
  ctx: RenderCtx,
  input: OrderFormV2Input,
  items: ReciprocalCommitmentItem[],
): void {
  startSection(pdf, ctx, input, "Reciprocal Value Commitments");
  let y = ctx.y;

  pdf.text(
    "Pricing reflects the value the customer agrees to share back. The commitments below are part of this proposal.",
    MARGIN_X,
    y,
    { size: 9, color: GREY },
  );
  y -= 18;

  for (const c of items) {
    if (y < MARGIN_BOTTOM + 50) {
      newPage(pdf, ctx, input);
      y = ctx.y;
    }
    const h = c.description ? 38 : 22;
    pdf.fillRect(MARGIN_X, y - h, PAGE_W - 2 * MARGIN_X, h, ASAFE_YELLOW_TINT);
    pdf.fillRect(MARGIN_X, y - h, 4, h, ASAFE_YELLOW);
    pdf.text(c.title, MARGIN_X + 14, y - 12, {
      font: "Helvetica-Bold",
      size: 10,
      color: BLACK,
    });
    if (typeof c.discountPct === "number" && c.discountPct > 0) {
      pdf.text(
        `${c.discountPct.toFixed(1)}%`,
        PAGE_W - MARGIN_X - 8,
        y - 12,
        { size: 11, font: "Helvetica-Bold", color: BLACK, align: "right" },
      );
    }
    if (c.description) {
      const wrapped = wrapLines(c.description, 110);
      let by = y - 24;
      for (const line of wrapped) {
        pdf.text(line, MARGIN_X + 14, by, { size: 8, color: GREY });
        by -= 10;
        if (by < y - h + 4) break;
      }
    }
    y -= h + 6;
  }

  ctx.y = y;
  renderFooter(pdf, ctx, input);
}

// ─── Section: approvals ────────────────────────────────────────────────────

function renderApprovals(
  pdf: PdfBuilder,
  ctx: RenderCtx,
  input: OrderFormV2Input,
): void {
  // Approvals fit on a single half-page; if there's no space, push to a
  // fresh page so signatures aren't broken.
  if (ctx.y < MARGIN_BOTTOM + 220) {
    newPage(pdf, ctx, input);
  }
  startSection(pdf, ctx, input, "Approvals");
  let y = ctx.y;

  const slots: Array<{ key: "technical" | "commercial" | "marketing"; label: string }> = [
    { key: "technical", label: "TECHNICAL APPROVAL" },
    { key: "commercial", label: "COMMERCIAL APPROVAL" },
  ];
  if (input.approvals.includeMarketing) {
    slots.push({ key: "marketing", label: "MARKETING APPROVAL" });
  }
  const cardW = (PAGE_W - 2 * MARGIN_X - (slots.length - 1) * 12) / slots.length;
  const cardH = 130;

  for (let i = 0; i < slots.length; i++) {
    const slot = slots[i];
    const cardX = MARGIN_X + i * (cardW + 12);
    pdf.fillRect(cardX, y - cardH, cardW, cardH, FAINT_GREY);
    pdf.fillRect(cardX, y - 22, cardW, 22, BLACK);
    pdf.text(slot.label, cardX + 10, y - 16, {
      font: "Helvetica-Bold",
      size: 10,
      color: ASAFE_YELLOW,
    });
    const sig = (input.approvals as any)[slot.key] as SignatureBlock | null | undefined;
    let yy = y - 36;
    pdf.text("NAME", cardX + 10, yy, {
      font: "Helvetica-Bold",
      size: 7,
      color: GREY,
    });
    pdf.text(sig?.signedBy || "—", cardX + 10, yy - 12, { size: 9, color: BLACK });
    yy -= 26;
    pdf.text("ROLE", cardX + 10, yy, {
      font: "Helvetica-Bold",
      size: 7,
      color: GREY,
    });
    pdf.text(sig?.jobTitle || "—", cardX + 10, yy - 12, { size: 9, color: BLACK });
    yy -= 26;
    pdf.text("DATE", cardX + 10, yy, {
      font: "Helvetica-Bold",
      size: 7,
      color: GREY,
    });
    pdf.text(
      sig?.signedAtIso ? sig.signedAtIso.slice(0, 10) : "—",
      cardX + 10,
      yy - 12,
      { size: 9, color: BLACK },
    );
    yy -= 26;
    // Signature line
    pdf.fillRect(cardX + 10, yy - 4, cardW - 20, 0.6, BLACK);
    pdf.text("Signature", cardX + 10, yy - 16, { size: 7, color: GREY });
    if (sig?.signed) {
      pdf.fillRect(cardX + 10, yy - 18, 80, 12, GREEN_DARK);
      pdf.text("APPROVED", cardX + 14, yy - 14, {
        font: "Helvetica-Bold",
        size: 8,
        color: WHITE,
      });
    }
  }

  y -= cardH + 8;
  ctx.y = y;
  renderFooter(pdf, ctx, input);
}

// ─── Section: terms and conditions ─────────────────────────────────────────

function renderTermsAndConditions(
  pdf: PdfBuilder,
  ctx: RenderCtx,
  input: OrderFormV2Input,
): void {
  if (ctx.y < MARGIN_BOTTOM + 280) {
    newPage(pdf, ctx, input);
  }
  startSection(pdf, ctx, input, "Terms & Conditions");
  let y = ctx.y;

  const tnc: Array<[string, string]> = [
    ["Validity", "Pricing valid for 30 days from the date on the cover."],
    [
      "Lead time",
      "10-12 weeks ex-works from receipt of approved order and 75% deposit. Subject to stock and engineering review.",
    ],
    [
      "Payment",
      "75% upfront on order, 25% prior to shipment. Bank details supplied on the proforma invoice. No CC details to be submitted in writing.",
    ],
    [
      "Warranty",
      "24 months from delivery against manufacturing defect. Impact damage covered to the certified joule rating only.",
    ],
    [
      "PAS 13",
      "All alignment statements are an indicative engineering interpretation of PAS 13:2017 - not a commercial-liability statement. Conservative interpretation applied throughout. Verify with A-SAFE engineering for procurement.",
    ],
    [
      "Site survey",
      "Where a site survey is included as an appendix, recommendations are based on observed conditions on the date of the survey. Material site changes may require a re-survey.",
    ],
  ];
  // Body column is narrower than the page width, so 90 chars/line keeps us
  // safely inside the right margin at size 9.
  const labelW = 80;
  const bodyMaxChars = 78;
  for (const [k, v] of tnc) {
    if (y < MARGIN_BOTTOM + 60) {
      newPage(pdf, ctx, input);
      y = ctx.y;
    }
    pdf.text(k.toUpperCase(), MARGIN_X, y, {
      font: "Helvetica-Bold",
      size: 8,
      color: ASAFE_YELLOW,
    });
    const wrapped = wrapLines(v, bodyMaxChars);
    // Indent every wrapped line to the body column so the rows line up
    // visually under the label cluster.
    for (const w of wrapped) {
      if (y < MARGIN_BOTTOM + 60) {
        newPage(pdf, ctx, input);
        y = ctx.y;
      }
      pdf.text(w, MARGIN_X + labelW, y, { size: 9, color: BLACK });
      y -= 11;
    }
    y -= 6;
  }

  ctx.y = y;
  renderFooter(pdf, ctx, input);
}

// ─── Section: site survey appendix ─────────────────────────────────────────

function renderSiteSurveyAppendix(
  pdf: PdfBuilder,
  ctx: RenderCtx,
  input: OrderFormV2Input,
  appendix: SiteSurveyAppendix,
): void {
  newPage(pdf, ctx, input);
  startSection(pdf, ctx, input, `Appendix - ${appendix.surveyTitle}`);
  let y = ctx.y;

  if (appendix.surveyDate) {
    pdf.text(`Survey date: ${appendix.surveyDate}`, MARGIN_X, y, {
      size: 9,
      color: GREY,
    });
    y -= 14;
  }
  if (appendix.layoutDrawingThumbnailNote) {
    pdf.text(appendix.layoutDrawingThumbnailNote, MARGIN_X, y, {
      size: 8,
      color: BLUE_LINK,
    });
    y -= 12;
  }
  y -= 4;

  for (const zone of appendix.zones) {
    if (y < MARGIN_BOTTOM + 90) {
      newPage(pdf, ctx, input);
      y = ctx.y;
    }
    const recRowCount = Math.max(0, (zone.recommendations || []).length);
    const blockH = 60 + Math.min(recRowCount, 4) * 12;
    pdf.fillRect(MARGIN_X, y - blockH, PAGE_W - 2 * MARGIN_X, blockH, FAINT_GREY);
    pdf.fillRect(MARGIN_X, y - 20, 4, 20, ASAFE_YELLOW);
    pdf.text(zone.zoneName, MARGIN_X + 14, y - 14, {
      font: "Helvetica-Bold",
      size: 10,
      color: BLACK,
    });
    if (zone.areaType) {
      pdf.text(`(${zone.areaType})`, MARGIN_X + 14 + 240, y - 14, {
        size: 9,
        color: GREY,
      });
    }
    pdf.text(
      `${zone.photoCount} photo${zone.photoCount === 1 ? "" : "s"} on file`,
      PAGE_W - MARGIN_X - 8,
      y - 14,
      { size: 8, color: GREY, align: "right" },
    );
    let yy = y - 28;
    if (zone.observations) {
      pdf.text("Observations:", MARGIN_X + 14, yy, {
        font: "Helvetica-Bold",
        size: 8,
        color: GREY,
      });
      yy -= 10;
      const wrapped = wrapLines(zone.observations, 100);
      for (const w of wrapped.slice(0, 2)) {
        pdf.text(w, MARGIN_X + 18, yy, { size: 8, color: BLACK });
        yy -= 10;
      }
    }
    if (zone.damageNotes) {
      pdf.text("Damage:", MARGIN_X + 14, yy, {
        font: "Helvetica-Bold",
        size: 8,
        color: RED_DARK,
      });
      yy -= 10;
      const wrapped = wrapLines(zone.damageNotes, 100);
      for (const w of wrapped.slice(0, 2)) {
        pdf.text(w, MARGIN_X + 18, yy, { size: 8, color: BLACK });
        yy -= 10;
      }
    }
    if (zone.recommendations && zone.recommendations.length > 0) {
      pdf.text("Recommended (per metre price):", MARGIN_X + 14, yy, {
        font: "Helvetica-Bold",
        size: 8,
        color: ASAFE_YELLOW,
      });
      yy -= 10;
      for (const r of zone.recommendations.slice(0, 4)) {
        const price =
          typeof r.pricePerMeter === "number"
            ? `${input.currency.toUpperCase()} ${formatMoney(r.pricePerMeter)} / m`
            : "(price TBD)";
        pdf.text(`- ${truncate(r.productName, 50)} - ${price}`, MARGIN_X + 18, yy, {
          size: 8,
          color: BLACK,
        });
        yy -= 10;
      }
    }
    y -= blockH + 8;
  }

  ctx.y = y;
  renderFooter(pdf, ctx, input);
}

// ─── Helpers shared across sections ────────────────────────────────────────

function startSection(
  pdf: PdfBuilder,
  ctx: RenderCtx,
  input: OrderFormV2Input,
  title: string,
): void {
  // If we're not on a page already (e.g. just finished cover), or we're
  // out of room, start a new one.
  if (ctx.y < MARGIN_BOTTOM + 200 || ctx.y === 0) {
    newPage(pdf, ctx, input);
  }
  // Section header bar: title bar at the top, yellow accent strip, breathing room.
  const y0 = ctx.y;
  pdf.fillRect(MARGIN_X, y0 - 24, PAGE_W - 2 * MARGIN_X, 24, BLACK);
  pdf.text(title.toUpperCase(), MARGIN_X + 12, y0 - 16, {
    font: "Helvetica-Bold",
    size: 12,
    color: ASAFE_YELLOW,
  });
  // Right-aligned reference. Sit it well clear of the band edge — our
  // approxStringWidth is an estimate, so 18pt of breathing room avoids
  // the trailing characters getting clipped at the page margin.
  pdf.text(input.referenceNumber, PAGE_W - MARGIN_X - 18, y0 - 16, {
    size: 8,
    color: WHITE,
    align: "right",
  });
  pdf.fillRect(MARGIN_X, y0 - 28, PAGE_W - 2 * MARGIN_X, 2, ASAFE_YELLOW);
  ctx.y = y0 - 38;
}

function newPage(pdf: PdfBuilder, ctx: RenderCtx, input: OrderFormV2Input): void {
  pdf.startPage();
  ctx.pageNum += 1;
  // Yellow header strip on every continuation page.
  pdf.fillRect(0, PAGE_H - 24, PAGE_W, 24, ASAFE_YELLOW);
  pdf.text("A-SAFE", MARGIN_X, PAGE_H - 16, {
    font: "Helvetica-Bold",
    size: 10,
    color: BLACK,
  });
  pdf.text("ENGAGE", MARGIN_X + 50, PAGE_H - 16, {
    font: "Helvetica-Bold",
    size: 9,
    color: BLACK,
  });
  pdf.text(
    `Order Form - ${input.referenceNumber}`,
    PAGE_W - MARGIN_X,
    PAGE_H - 16,
    { font: "Helvetica-Bold", size: 9, color: BLACK, align: "right" },
  );
  ctx.y = PAGE_H - 40;
}

function renderFooter(
  pdf: PdfBuilder,
  _ctx: RenderCtx,
  input: OrderFormV2Input,
): void {
  const stamp = input.generatedAt.toISOString().slice(0, 16) + " UTC";
  const lineY = MARGIN_BOTTOM - 22;
  pdf.fillRect(MARGIN_X, lineY + 14, PAGE_W - 2 * MARGIN_X, 1.5, ASAFE_YELLOW);
  // Top line: reference (left) + generation timestamp (right). Both are
  // short enough to never collide.
  pdf.text(
    `A-SAFE Engage - ${input.referenceNumber}`,
    MARGIN_X,
    lineY,
    { font: "Helvetica-Bold", size: 8, color: BLACK },
  );
  pdf.text(`Generated ${stamp}.`, PAGE_W - MARGIN_X, lineY, {
    size: 7,
    color: GREY,
    align: "right",
  });
  // Bottom line: short disclaimer (left) + standards link (right). The
  // disclaimer is intentionally trimmed so the right-aligned URL can sit
  // on the same line without colliding.
  pdf.text(
    "Indicative engineering interpretation of PAS 13:2017.",
    MARGIN_X,
    lineY - 10,
    { size: 7, color: GREY },
  );
  pdf.text(
    `${input.appOrigin}${PAS13_PDF_URL}`,
    PAGE_W - MARGIN_X,
    lineY - 10,
    { size: 7, color: BLUE_LINK, align: "right" },
  );
}

function verdictLabel(v: Verdict): string {
  return v === "aligned"
    ? "PAS 13 aligned"
    : v === "borderline"
      ? "Borderline"
      : "Not aligned";
}

function computeSafetyFactor(
  productJoules: number | null | undefined,
  requiredJoules: number | null | undefined,
): number {
  if (!productJoules || !requiredJoules || requiredJoules <= 0) return 0;
  return productJoules / requiredJoules;
}

function truncate(s: string, n: number): string {
  if (!s) return "";
  if (s.length <= n) return s;
  return s.slice(0, Math.max(0, n - 1)).trimEnd() + "…";
}

function wrapLines(s: string, maxChars: number): string[] {
  const out: string[] = [];
  if (!s) return out;
  const lines = s.split(/\n/);
  for (const ln of lines) {
    const words = ln.split(/\s+/);
    let line = "";
    for (const w of words) {
      if ((line + " " + w).trim().length <= maxChars) {
        line = (line + " " + w).trim();
      } else {
        if (line) out.push(line);
        line = w;
      }
    }
    if (line) out.push(line);
  }
  return out;
}

function formatMoney(n: number): string {
  const v = Number.isFinite(n) ? n : 0;
  // 2-decimal places for currency, with thousands separators. The
  // currency code itself is appended by the caller.
  return v.toLocaleString("en-US", {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  });
}

function formatDate(d: Date): string {
  // "20 Apr 2026" - matches the in-app convention.
  const day = d.getUTCDate();
  const month = d.toLocaleString("en-GB", { month: "short", timeZone: "UTC" });
  const year = d.getUTCFullYear();
  return `${day} ${month} ${year}`;
}

function countDistinct(arr: string[]): number {
  return new Set(arr).size;
}

// ─── Convenience: build an impact scenario from a vehicle row ──────────────

/**
 * Pure helper: given a vehicle scenario (mass, speed, angle) and an optional
 * product impact rating, run pas13Verdict() and project onto the
 * `ImpactScenarioForReport` shape this PDF expects. Used by the route layer
 * so the impact-summary section stays in sync with the alignment-report
 * verdict logic.
 */
export function makeImpactScenario(args: {
  vehicleLabel: string;
  vehicleMassKg: number;
  loadMassKg?: number;
  speedKmh: number;
  approachAngleDeg: number;
  productRatedJoulesAt45deg?: number;
  productImpactZoneMaxMm?: number;
}): ImpactScenarioForReport {
  const verdict = pas13Verdict({
    vehicleMassKg: args.vehicleMassKg,
    loadMassKg: args.loadMassKg,
    speedKmh: args.speedKmh,
    approachAngleDeg: args.approachAngleDeg,
    productRatedJoulesAt45deg: args.productRatedJoulesAt45deg ?? 0,
    productImpactZoneMaxMm: args.productImpactZoneMaxMm ?? 200,
  });
  // Reported KE at the actual approach angle (informational alongside the
  // 45° figure).
  const m = (args.vehicleMassKg + (args.loadMassKg ?? 0));
  const vMs = args.speedKmh / 3.6;
  const sin = Math.sin((args.approachAngleDeg * Math.PI) / 180);
  const appliedJoules = 0.5 * m * (vMs * sin) * (vMs * sin);
  return {
    vehicleLabel: args.vehicleLabel,
    vehicleMassKg: args.vehicleMassKg,
    loadMassKg: args.loadMassKg ?? 0,
    speedKmh: args.speedKmh,
    approachAngleDeg: args.approachAngleDeg,
    appliedJoules,
    joulesAt45: verdict.details.requiredJoulesAt45deg,
    verdict: verdict.verdict,
    safetyMarginPct: verdict.details.safetyMarginPct,
  };
}

/** Build the standard PAS 13 threshold ladder for the bar plot. */
export function defaultPas13Thresholds(): Array<{ label: string; joules: number }> {
  return [
    { label: "T1 / T2", joules: 11000 },
    { label: "T3", joules: 17000 },
    { label: "T4", joules: 30000 },
  ];
}

/** Convenience for callers that produce a flat list of citation IDs. */
export function citationsForSections(sections: string[]): Pas13Citation[] {
  const out: Pas13Citation[] = [];
  for (const s of sections) {
    const c = pas13Cite(s);
    if (c) out.push(c);
  }
  return out;
}

// ─── PdfBuilder — minimal PDF 1.4 byte writer ──────────────────────────────
//
// Identical shape to quoteDraftPdf.ts and pas13AlignmentReportPdf.ts. We
// deliberately duplicate because (a) the three PDFs have meaningfully
// different layouts, (b) the builder surface is small (~200 lines), and (c)
// extracting a shared base while the layouts are still settling would slow
// down iteration. Once a fourth PDF type emerges and the duplication
// hurts, we extract a `worker/lib/pdfCore.ts` and refactor callers in one
// pass.
// ────────────────────────────────────────────────────────────────────────────

const PAGE_W = 595; // A4 portrait
const PAGE_H = 842;
const MARGIN_X = 36;
const MARGIN_BOTTOM = 60;

const ASAFE_YELLOW: RGB = [1.0, 0.78, 0.17]; // #FFC72C
const ASAFE_YELLOW_TINT: RGB = [1.0, 0.94, 0.78];
const BLACK: RGB = [0.1, 0.1, 0.18];
const WHITE: RGB = [1, 1, 1];
const GREY: RGB = [0.42, 0.42, 0.47];
const FAINT_GREY: RGB = [0.95, 0.95, 0.96];
const GREEN_DARK: RGB = [0.1, 0.5, 0.27];
const AMBER_DARK: RGB = [0.85, 0.55, 0.07];
const RED_DARK: RGB = [0.78, 0.15, 0.15];
const BLUE_LINK: RGB = [0.16, 0.32, 0.78];

type RGB = [number, number, number];

interface RenderCtx {
  /** Current vertical cursor on the page. 0 means "no page yet". */
  y: number;
  pageNum: number;
  totalPages: number;
}

/** Shared shape for the small table-rendering helpers (vehicles, impact,
 *  pricing). Keeping `align` optional avoids "as const" gymnastics in each
 *  call site while still narrowing correctly inside the loop body. */
interface TableColumn {
  x: number;
  w: number;
  label: string;
  align?: "right";
}

interface TextOptions {
  font?: "Helvetica" | "Helvetica-Bold";
  size?: number;
  color?: RGB;
  align?: "left" | "right" | "center";
}

class PdfBuilder {
  private objects: Array<string | Uint8Array> = [];
  private pages: number[] = [];
  private currentContent: string[] = [];
  private currentPageId: number | null = null;
  private finalised: false | { bytes: Uint8Array } = false;

  constructor() {
    this.objects.push("");
    this.objects.push("");
    this.objects.push("");
    this.objects.push(this.fontObject("Helvetica"));
    this.objects.push(this.fontObject("Helvetica-Bold"));
  }

  startPage(): void {
    if (this.currentPageId !== null) this.flushPage();
    this.objects.push("");
    this.currentPageId = this.objects.length - 1;
    this.currentContent = [];
  }

  finalise(): void {
    if (this.currentPageId !== null) this.flushPage();
    if (this.finalised) return;

    this.objects[1] = `<< /Type /Catalog /Pages 2 0 R >>`;
    const kids = this.pages.map((id) => `${id} 0 R`).join(" ");
    this.objects[2] = `<< /Type /Pages /Kids [${kids}] /Count ${this.pages.length} >>`;

    const parts: Uint8Array[] = [];
    const enc = new TextEncoder();
    parts.push(enc.encode("%PDF-1.4\n%\xC3\xA1\xC3\xA9\xC3\xAD\xC3\xB3\n"));

    const offsets: number[] = [];
    let cursor = parts[0].byteLength;
    offsets.push(0);

    for (let i = 1; i < this.objects.length; i++) {
      const body = this.objects[i];
      offsets.push(cursor);
      const header = `${i} 0 obj\n`;
      const footer = `\nendobj\n`;
      const headerBytes = enc.encode(header);
      const footerBytes = enc.encode(footer);
      const bodyBytes = typeof body === "string" ? enc.encode(body) : body;
      parts.push(headerBytes, bodyBytes, footerBytes);
      cursor += headerBytes.byteLength + bodyBytes.byteLength + footerBytes.byteLength;
    }

    const xrefStart = cursor;
    let xref = `xref\n0 ${this.objects.length}\n`;
    xref += `0000000000 65535 f \n`;
    for (let i = 1; i < this.objects.length; i++) {
      xref += `${String(offsets[i]).padStart(10, "0")} 00000 n \n`;
    }
    parts.push(enc.encode(xref));
    parts.push(
      enc.encode(
        `trailer\n<< /Size ${this.objects.length} /Root 1 0 R >>\nstartxref\n${xrefStart}\n%%EOF\n`,
      ),
    );

    let total = 0;
    for (const p of parts) total += p.byteLength;
    const out = new Uint8Array(total);
    let off = 0;
    for (const p of parts) {
      out.set(p, off);
      off += p.byteLength;
    }
    this.finalised = { bytes: out };
  }

  bytes(): Uint8Array {
    if (!this.finalised) throw new Error("PdfBuilder.finalise() not called");
    return this.finalised.bytes;
  }

  fillRect(x: number, y: number, w: number, h: number, color: RGB): void {
    this.currentContent.push(
      `${color[0].toFixed(3)} ${color[1].toFixed(3)} ${color[2].toFixed(3)} rg`,
      `${x.toFixed(2)} ${y.toFixed(2)} ${w.toFixed(2)} ${h.toFixed(2)} re f`,
    );
  }

  text(value: string, x: number, y: number, opts: TextOptions = {}): void {
    const font = opts.font ?? "Helvetica";
    const size = opts.size ?? 10;
    const color = opts.color ?? BLACK;
    const fontRef = font === "Helvetica-Bold" ? "F2" : "F1";
    const escaped = pdfEscape(value);

    let drawX = x;
    if (opts.align === "right") {
      const w = approxStringWidth(value, size, font === "Helvetica-Bold");
      drawX = x - w;
    } else if (opts.align === "center") {
      const w = approxStringWidth(value, size, font === "Helvetica-Bold");
      drawX = x - w / 2;
    }

    this.currentContent.push(
      `BT`,
      `/${fontRef} ${size} Tf`,
      `${color[0].toFixed(3)} ${color[1].toFixed(3)} ${color[2].toFixed(3)} rg`,
      `${drawX.toFixed(2)} ${y.toFixed(2)} Td`,
      `(${escaped}) Tj`,
      `ET`,
    );
  }

  private flushPage(): void {
    const pageId = this.currentPageId!;
    const content = this.currentContent.join("\n");
    const contentId = this.objects.length;
    const stream = `<< /Length ${content.length} >>\nstream\n${content}\nendstream`;
    this.objects.push(stream);

    const pageDict =
      `<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${PAGE_W} ${PAGE_H}] ` +
      `/Contents ${contentId} 0 R ` +
      `/Resources << /Font << /F1 3 0 R /F2 4 0 R >> >> >>`;
    this.objects[pageId] = pageDict;
    this.pages.push(pageId);

    this.currentPageId = null;
    this.currentContent = [];
  }

  private fontObject(name: "Helvetica" | "Helvetica-Bold"): string {
    return `<< /Type /Font /Subtype /Type1 /BaseFont /${name} /Encoding /WinAnsiEncoding >>`;
  }
}

function pdfEscape(s: string): string {
  return s
    .replace(/\\/g, "\\\\")
    .replace(/\(/g, "\\(")
    .replace(/\)/g, "\\)")
    .replace(/[-￿]/g, (ch) => {
      // Map common typographic chars to ASCII first.
      if (ch === "—") return "-";       // em dash
      if (ch === "–") return "-";       // en dash
      if (ch === "·") return "-";       // middle dot
      if (ch === "…") return "...";     // ellipsis
      if (ch === "→") return "->";      // arrow
      if (ch === "×") return "x";       // multiplication sign
      if (ch === "‘" || ch === "’") return "'";   // curly single
      if (ch === "“" || ch === "”") return '"';   // curly double
      // For chars we want rendered verbatim under WinAnsiEncoding, emit a
      // PDF octal escape (\nnn). Our content stream is UTF-8 encoded
      // (TextEncoder), so a literal Latin-1 byte 0xB0 would arrive at the
      // PDF parser as the two UTF-8 bytes \xC2\xB0, rendering "Â°". Octal
      // escapes are read by the PDF parser as a single-byte value, which
      // the font's /Encoding /WinAnsiEncoding then maps to the right glyph.
      if (ch === "°") return "\\260"; // 0xB0 = degree sign
      if (ch === "²") return "\\262"; // 0xB2 = superscript two
      if (ch === "§") return "\\247"; // 0xA7 = section sign
      return "?";
    });
}

function approxStringWidth(s: string, size: number, bold: boolean): number {
  // Helvetica avg glyph width is ~0.50 em for regular and ~0.54 em for
  // bold across the full character set. We bias up by ~5% so right-
  // aligned text never overruns the right edge of its container — an
  // extra pixel of breathing room is harmless and the alternative
  // (clipping) is a real visual bug.
  const factor = bold ? 0.56 : 0.52;
  return s.length * size * factor;
}
