// GENERATED by scripts/embedBrandAssets.ts — do not edit by hand.
// Re-run `npx tsx scripts/embedBrandAssets.ts` after changing the PNGs.

export { LOGO_PRIMARY_B64 } from "./logoPrimary";
export { LOGO_SECONDARY_B64 } from "./logoSecondary";
export { LOGO_SMALL_B64 } from "./logoSmall";
export { ICON_YELLOW_B64 } from "./iconYellow";
export { ICON_BLACK_B64 } from "./iconBlack";
