/**
 * Downloads all licence-safe vehicle thumbnails from Wikimedia Commons
 * to client/public/assets/vehicles/{slug}.{ext}. Source list is
 * scripts/data/vehicle-image-map.json (kept under source control so
 * the attribution trail is preserved).
 *
 * Reason for local-hosting: Wikimedia aggressively rate-limits
 * hotlinking from browsers (we saw HTTP 429 in testing), which broke
 * the Impact Calculator vehicle cards in prod. Serving from our own
 * Assets binding removes that dependency entirely.
 *
 * Usage:
 *   npx tsx scripts/downloadVehicleImages.ts
 *
 * Re-run is idempotent; files that already exist are skipped unless
 * --force is passed.
 */
import { readFile, writeFile, access, mkdir } from "node:fs/promises";
import { resolve, extname, dirname } from "node:path";

const MAP_PATH = resolve("scripts/data/vehicle-image-map.json");
const OUT_DIR = resolve("client/public/assets/vehicles");
const USER_AGENT =
  "asafe-engage-cf/1.0 (https://asafe-engage.tom-d-g-childs.workers.dev; ops@asafe-engage)";

function slugify(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

function extForUrl(url: string): string {
  const m = url.toLowerCase().match(/\.(jpg|jpeg|png|gif|webp)(?:$|\?)/);
  return m ? (m[1] === "jpeg" ? ".jpg" : `.${m[1]}`) : ".jpg";
}

async function fileExists(p: string): Promise<boolean> {
  try {
    await access(p);
    return true;
  } catch {
    return false;
  }
}

async function main() {
  const force = process.argv.includes("--force");
  const raw = await readFile(MAP_PATH, "utf8");
  const data = JSON.parse(raw) as {
    vehicles: Array<{
      id: string;
      name: string;
      imageUrl: string;
      source?: string;
      licence?: string;
    }>;
  };

  await mkdir(OUT_DIR, { recursive: true });
  const results: Array<{ name: string; slug: string; localPath: string; skipped?: boolean; bytes?: number; error?: string }> = [];

  for (const v of data.vehicles) {
    const slug = slugify(v.name);
    const ext = extForUrl(v.imageUrl);
    const localFile = `${slug}${ext}`;
    const localPath = `${OUT_DIR}/${localFile}`;
    const publicPath = `/assets/vehicles/${localFile}`;

    if (!force && (await fileExists(localPath))) {
      results.push({ name: v.name, slug, localPath: publicPath, skipped: true });
      console.log(`[skip] ${v.name} → ${publicPath}`);
      continue;
    }

    try {
      const res = await fetch(v.imageUrl, { headers: { "User-Agent": USER_AGENT } });
      if (!res.ok) {
        results.push({ name: v.name, slug, localPath: publicPath, error: `HTTP ${res.status}` });
        console.warn(`[fail] ${v.name} → HTTP ${res.status}`);
        continue;
      }
      const buf = Buffer.from(await res.arrayBuffer());
      await writeFile(localPath, buf);
      results.push({ name: v.name, slug, localPath: publicPath, bytes: buf.length });
      console.log(`[ok]   ${v.name} → ${publicPath} (${buf.length} bytes)`);
      // Gentle pacing — Wikimedia rate-limits aggressively. 3s spacing
      // keeps us well under the 1 req/s threshold they enforce per-UA.
      await new Promise((r) => setTimeout(r, 3000));
    } catch (err) {
      results.push({
        name: v.name,
        slug,
        localPath: publicPath,
        error: err instanceof Error ? err.message : String(err),
      });
      console.error(`[err]  ${v.name}:`, err);
    }
  }

  // Write out a companion JSON that maps vehicle name → local public path
  // so the admin migration endpoint can apply these to the DB.
  const applyMapPath = resolve("scripts/data/vehicle-image-map-local.json");
  const applyMap = {
    _meta: {
      generatedAt: new Date().toISOString(),
      notes: "Local public paths under /assets/vehicles/ served by the Cloudflare ASSETS binding. Re-generated by scripts/downloadVehicleImages.ts.",
    },
    vehicles: results
      .filter((r) => !r.error)
      .map((r) => ({ name: r.name, localPath: r.localPath })),
  };
  await writeFile(applyMapPath, JSON.stringify(applyMap, null, 2));
  console.log(`\nWrote apply-map → ${applyMapPath}`);

  const ok = results.filter((r) => !r.error && !r.skipped).length;
  const skipped = results.filter((r) => r.skipped).length;
  const failed = results.filter((r) => r.error).length;
  console.log(`\nDone: ${ok} downloaded, ${skipped} skipped, ${failed} failed`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
