// ────────────────────────────────────────────────────────────────────────────
// scripts/embedBrandAssets.ts
//
// Converts the A-SAFE logo / icon PNGs under attached_assets/ into TypeScript
// modules under worker/assets/brand/ that export a base64 string each. The
// Worker imports those modules and decodes them at runtime with atob(), so
// the PDF renderer never has to fetch a logo over the network.
//
// Usage:  npx tsx scripts/embedBrandAssets.ts
// Re-run whenever the source PNGs change. Output is deterministic.
// ────────────────────────────────────────────────────────────────────────────

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const src = resolve(root, "attached_assets/A-SAFE_Logo_Assets");
const out = resolve(root, "worker/assets/brand");

interface Asset {
  /** Exported constant name. */
  name: string;
  /** Output file (without extension) under worker/assets/brand/. */
  file: string;
  /** Source PNG relative to attached_assets/A-SAFE_Logo_Assets/. */
  source: string;
  /** One-line note for the generated header. */
  note: string;
}

const ASSETS: Asset[] = [
  {
    name: "LOGO_PRIMARY_B64",
    file: "logoPrimary",
    source: "LOGO/PNG/A-SAFE_Logo_Strapline_Primary_Version.png",
    note: "Strapline logo, yellow + white on transparent. Use on black bands.",
  },
  {
    name: "LOGO_SECONDARY_B64",
    file: "logoSecondary",
    source: "LOGO/PNG/A-SAFE_Logo_Strapline_Secondary_Version.png",
    note: "Strapline logo, yellow icon + black word. Use on white.",
  },
  {
    name: "LOGO_SMALL_B64",
    file: "logoSmall",
    source: "LOGO/PNG/A-SAFE_Logo_Secondary_Version.png",
    note: "Logo without strapline. Small placements on white (min 20 mm wide).",
  },
  {
    name: "ICON_YELLOW_B64",
    file: "iconYellow",
    source: "ICON/PNG/A-SAFE_Icon_Yellow_Version.png",
    note: "Safety-halo icon, yellow. Footer / bullet use on black.",
  },
  {
    name: "ICON_BLACK_B64",
    file: "iconBlack",
    source: "ICON/PNG/A-SAFE_Icon_Black_Version.png",
    note: "Safety-halo icon, black. Footer use on white.",
  },
];

mkdirSync(out, { recursive: true });

const index: string[] = [
  "// GENERATED by scripts/embedBrandAssets.ts — do not edit by hand.",
  "// Re-run `npx tsx scripts/embedBrandAssets.ts` after changing the PNGs.",
  "",
];

for (const a of ASSETS) {
  const bytes = readFileSync(resolve(src, a.source));
  const b64 = bytes.toString("base64");
  const body = [
    "// GENERATED by scripts/embedBrandAssets.ts — do not edit by hand.",
    `// Source: attached_assets/A-SAFE_Logo_Assets/${a.source} (${bytes.length} bytes, PNG)`,
    `// ${a.note}`,
    `export const ${a.name} = "${b64}";`,
    "",
  ].join("\n");
  writeFileSync(resolve(out, `${a.file}.ts`), body);
  index.push(`export { ${a.name} } from "./${a.file}";`);
  console.log(`${a.file}.ts  <- ${a.source}  (${bytes.length} bytes)`);
}

writeFileSync(resolve(out, "index.ts"), index.join("\n") + "\n");
console.log(`wrote ${ASSETS.length} modules + index.ts to ${out}`);
